version: "3.7"
services:
  frontend:
    image: node:12-alpine
    command: sh -c "serve -s -l 3000"
    ports:
      - 3000:80
  backend:
    image: node:12-alpine
    command: sh -c "node server.js"